### ISSUE TITLE
error

### ISSUE THREAD

**Issue by MikhailY** [Flynrod/FeatherSpawn#1]
featherspawn 1.9.2
paperspigot 1.12.2
https://hasteb.in/isigeliqek.profile

**Comment by Flynrod** [comment]
Is it when you perform a specific action (such as executing a command) or when starting up?

**Comment by Flynrod** [comment]
### Problem identified:
FeatherSpawn's security is not compatible with the PlugMan plugin. Each interaction of PlugMan with FeatherSpawn produces error logs.

**Comment by Flynrod** [comment]
Fixed with [**1.9.5 update**](https://www.spigotmc.org/resources/featherspawn.38865/update?update=214338)!
