### ISSUE TITLE
Keep the fly after a fight

### ISSUE THREAD

**Issue by Rasturize** [Flynrod/FeatherSpawn#13]
Plugins: http://rasturize.com/i/a9dd0c.png
Server version: TacoSpigot 1.8.8
FeatherSpawn version: latest

When coming out of a combat tag, if you previously had fly enabled before going into pvp, you have to re-enable fly for it to work. (Essentials fly)

**Comment by Flynrod** [comment]
Fixed with [1.9.82 update](https://www.spigotmc.org/resources/featherspawn.38865/update?update=218245)!
