### ISSUE TITLE
Startup error

### ISSUE THREAD

**Issue by Rasturize** [Flynrod/FeatherSpawn#6]
plugins: http://rasturize.com/i/4077bb.png
server version: Paper 1.8.8
plugin version: latest

Plugin errors on startup, error: https://ghostbin.com/paste/3b5tb

**Comment by Flynrod** [comment]
Thanks for your bug report! This SHA-256 bug occurs when you're downloading FeatherSpawn with SpigotMC.org.

**Comment by Flynrod** [comment]
Should be fixed with [1.9.71 update](https://www.spigotmc.org/resources/featherspawn-40-off.38865/update?update=216825), could you test it and tell me if it work?

**Comment by Rasturize** [comment]
Working now!

Thanks for the quick support <3
